##
## Contenedor de Superset
##
services:
  superset_srv:
    build: .
    image: local/superset-postgres:latest
    container_name: superset
    ports:
      - "8088:8088"
      - "5008:5008"
    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET__SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@host.docker.internal:${PG_PORT}/${PG_DB}?options=-csearch_path%3Dsuperset
      SUPERSET_ADMIN_USERNAME: ${SUPERSET_ADMIN_USERNAME}
      SUPERSET_ADMIN_FIRSTNAME: ${SUPERSET_ADMIN_FIRSTNAME}
      SUPERSET_ADMIN_LASTNAME: ${SUPERSET_ADMIN_LASTNAME}
      SUPERSET_ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL}
      SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD}
      MCP_DEV_USERNAME: ${MCP_DEV_USERNAME}
    volumes:
      - ./superset_data:/var/lib/superset
    command:
      - /bin/bash
      - -c
      - |
        superset db upgrade &&
        superset fab create-admin --username "$$SUPERSET_ADMIN_USERNAME" --firstname "$$SUPERSET_ADMIN_FIRSTNAME" --lastname "$$SUPERSET_ADMIN_LASTNAME" --email "$$SUPERSET_ADMIN_EMAIL" --password "$$SUPERSET_ADMIN_PASSWORD" &&
        superset load_examples &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  superset_data:
